### ISSUE TITLE
Can't set negative Axis value for DualShock 4 controller

### ISSUE THREAD

**Issue by stylerhun** [ViGEm/ViGEm.NET#12] opened 2021-01-28 15:22 UTC
**Describe the bug**
If I use controller.SetAxisValue, can't set negative axis value for DualShock4Axis.RightThumbX, just positive. How can I move the thumb sticks to the opposite direction? The SetAxis value's second parameter is byte.

**To Reproduce**
Use controller.SetAxisValue(DualShock4Axis.RightThumbX, -10);

**Expected behavior**
Can set positive and negative values as well for Axis

**Comment by Ryochan7** [comment] 2021-01-28 17:30
-10 is an invalid value for the DS4 stick axis. The range of the value (as reported by the hardware) is a full byte [0-255] with RS Left represented as [0-127], the neutral value represented as 128, and RS Right as [129-255]. It looks like you would actually want to pass value 118 as the second parameter to set the value 10 units to the left of neutral. The API is working as intended.

**Comment by stylerhun** [comment] 2021-01-28 17:58
> -10 is an invalid value for the DS4 stick axis. The range of the value (as reported by the hardware) is a full byte [0-255] with RS Left represented as [0-127], the neutral value represented as 128, and RS Right as [129-255]. It looks like you would actually want to pass value 118 as the second parameter to set the value 10 units to the left of neutral. The API is working as intended.

Oh, thank you very much for response. It's working now. I couldn't find anywhere the right values :)
Awesome library by the way, thank you!

**Comment by nefarius** [comment] 2021-02-18 11:40
I take the liberty to close this one 😉

**Closed as completed by nefarius** 2021-02-18 11:40 UTC
